# Generated by Django 5.2.4 on 2026-06-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', max_length=5),
        ),
        migrations.CreateModel(
            name='HostSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=False)),
                ('result_message', models.TextField(blank=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_search_history', to='Clientes.cliente')),
            ],
            options={
                'verbose_name_plural': 'host search histories',
                'ordering': ['-searched_at'],
            },
        ),
    ]
